name: macOS

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Environment
      run: |
        chmod +x .github/workflows/setup.sh
        sudo .github/workflows/setup.sh "Alone215" "Alone215" "${{ secrets.NGROK_AUTH_TOKEN }}"

    - name: Wait for Ngrok Tunnel to Start
      run: |
        sleep 10
        echo "Fetching public ngrok URL..."
        curl --silent http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[] | select(.proto=="tcp") | .public_url'

    - name: Setup tmate session (keep job alive)
      uses: mxschmitt/action-tmate@v2
      timeout-minutes: 9999
