name: macOS VNC Access
on: workflow_dispatch

jobs:
  start-macos:
    runs-on: macos-15
    timeout-minutes: 360

    steps:
      - name: Enable screen sharing (VNC)
        run: |
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
            -activate -configure -access -on -restart -agent -privs -all
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
            -configure -users runneradmin -access -on -privs -all
          echo -n 'P@ssw0rd' | iconv -t UTF-16LE | openssl md5 -binary | base64 > ~/vncpw
          sudo defaults write /Library/Preferences/com.apple.VNCSettings Password -data "$(cat ~/vncpw | base64 --decode | xxd -p)"
          sudo chmod 600 /Library/Preferences/com.apple.VNCSettings
          sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.screensharing.plist

      - name: Install ngrok
        run: |
          brew install ngrok jq
          echo "authtoken: ${{ secrets.NGROK_AUTH_TOKEN }}" > ~/.ngrok2/ngrok.yml

      - name: Start ngrok tunnel for VNC (port 5900)
        run: |
          nohup ngrok tcp 5900 --log=stdout > ngrok.log &
          sleep 10
          curl -s http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url'

      - name: Keep session alive for 6 hours
        run: |
          echo "✅ VNC server is running."
          echo "📌 Username: runneradmin"
          echo "🔑 Password: P@ssw0rd"
          echo "🕒 Keeping session alive..."
          sleep 216000  # 6 hours
