name: macOS 15 RDP Access

on:
  workflow_dispatch:

jobs:
  start-macos:
    runs-on: macos-15
    timeout-minutes: 360 # 6 hours

    steps:
      - name: Create new user "runneradmin"
        run: |
          sudo sysadminctl -addUser runneradmin -password 'P@ssw0rd!' -admin
          sudo dscl . -create /Users/runneradmin IsHidden 0
          echo "User created: runneradmin"

      - name: Set VNC Password
        run: |
          echo 'P@ssw0rd!' | perl -we 'print pack("H*", crypt(<STDIN>, "VN")."\0"x128)' > ~/.vncpass
          sudo mv ~/.vncpass /Library/Preferences/com.apple.VNCSettings.txt
          sudo chmod 600 /Library/Preferences/com.apple.VNCSettings.txt

      - name: Enable Screen Sharing (VNC)
        run: |
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
            -activate -configure -access -on -users runneradmin -privs -all \
            -restart -agent -menu

      - name: Enable VNC Access
        run: |
          sudo defaults write /Library/Preferences/com.apple.RemoteManagement VNCOnly -bool false
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -restart -agent

      - name: Install and Start ngrok
        run: |
          brew install ngrok
          echo "authtoken: YOUR_NGROK_AUTH_TOKEN" > ~/.ngrok2/ngrok.yml
          ngrok tcp 5900 &

      - name: Show VNC Connection Info
        run: sleep 10 && curl -s http://127.0.0.1:4040/api/tunnels

      - name: Keep Runner Alive
        run: |
          echo "macOS is running. Keeping alive for 6 hours..."
          while true; do sleep 60; done
