name: macOS 15 Desktop via VNC

on: workflow_dispatch

jobs:
  desktop:
    runs-on: macos-15
    steps:
      - name: Install TigerVNC and ngrok
        run: |
          brew install tigervnc ngrok jq
          
      - name: Set up VNC password and xstartup
        run: |
          mkdir -p ~/.vnc
          echo "macvnc123" | vncpasswd -f > ~/.vnc/passwd
          chmod 600 ~/.vnc/passwd
          echo "#!/bin/sh" > ~/.vnc/xstartup
          echo "open -a Finder" >> ~/.vnc/xstartup
          chmod +x ~/.vnc/xstartup

      - name: Start VNC Server
        run: |
          vncserver :1
          
      - name: Start ngrok tunnel
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        run: |
          ngrok config add-authtoken "$NGROK_AUTH_TOKEN"
          nohup ngrok tcp 5901 --log=stdout > ngrok.log &
          sleep 10
          echo "Ngrok tunnel address:"
          curl -s http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url'
