name: macOS 15 Desktop via RDP
on: workflow_dispatch
jobs:
  desktop:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Install xRDP
        run: |
          brew install xrdp
          sudo brew services start xrdp
      - name: Install ngrok and auth
        run: |
          brew install ngrok jq
          ngrok config add-authtoken "${{ secrets.NGROK_AUTH_TOKEN }}"
      - name: Start ngrok tunnel
        run: |
          nohup ngrok tcp 3389 --log=stdout &
          sleep 10
          curl -s http://127.0.0.1:4040/api/tunnels \
            | jq -r '.tunnels[0].public_url'
