name: macOS 15 VNC via Ngrok

on: workflow_dispatch

jobs:
  desktop:
    runs-on: macos-15
    steps:
      - name: Install ngrok and dependencies
        run: |
          brew install ngrok jq

      - name: Set VNC password and start screen sharing
        run: |
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
            -activate -configure -access -on -users runneradmin \
            -privs -all -restart -agent -menu
          echo "Setting VNC password..."
          echo -n "P@ssword!" | perl -we 'print pack("H*", crypt(<STDIN>, "aa"))' > ~/vncpwd
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
            -configure -clientopts -setvnclegacy -vnclegacy yes
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
            -configure -clientopts -setvncpw -vncpw "$(cat ~/vncpwd)"

      - name: Start ngrok tunnel for VNC (port 5900)
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        run: |
          ngrok config add-authtoken "$NGROK_AUTH_TOKEN"
          nohup ngrok tcp 5900 --log=stdout > ngrok.log &
          sleep 10
          echo "🔗 VNC Tunnel:"
          curl -s http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url'
