name: macOS 15 Desktop via VNC

on: workflow_dispatch

jobs:
  run-macos-vnc:
    runs-on: macos-15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ngrok and jq
        run: |
          brew install ngrok jq

      - name: Authenticate Ngrok
        run: |
          ngrok config add-authtoken "${{ secrets.NGROK_AUTH_TOKEN }}"

      - name: Enable Screen Sharing (VNC)
        run: |
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
            -activate -configure -access -on -restart -agent -privs -all

          sudo defaults write /Library/Preferences/com.apple.RemoteManagement VNCAlwaysStartOnConsole -bool true
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -restart

          echo "VNC is enabled. Setting password..."
          echo -n 'pass123' | perl -we 'print pack("H*", crypt(<STDIN>, "VN"))' > /tmp/vncpass
          sudo cp /tmp/vncpass /Library/Preferences/com.apple.VNCSettings.txt
          sudo chmod 600 /Library/Preferences/com.apple.VNCSettings.txt

      - name: Start ngrok tunnel for VNC
        run: |
          nohup ngrok tcp 5900 --log=stdout &
          sleep 10
          echo "Your VNC connection address is:"
          curl -s http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url'

      - name: Keep runner alive for VNC access
        run: tail -f /dev/null
